NexmoDotnetCodeSnippets/Controllers/ConversationController.cs
using Microsoft.AspNetCore.Mvc;
using Nexmo.Api.Conversations;
using NexmoDotnetCodeSnippets.Senders;

namespace NexmoDotnetCodeSnippets.Controllers
{
    public class ConversationController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CreateConversation(string name, string displayName, string imageUrl)
        {
            var response = ConversationSender.CreateConversation(name, displayName, imageUrl);
            ViewBag.CreateDisplayName = response.DisplayName;
            ViewBag.CreateId = response.Id;
            ViewBag.CreateImageUrl = response.ImageUrl;
            ViewBag.CreateSelf = response.Links.Self.Href;
            ViewBag.CreateName = response.Name;
            ViewBag.CreateProperties = response.Properties;
            ViewBag.CreateTimestamp = response.Timestamp;

            return View("index");
        }

        [HttpPost]
        public IActionResult GetConversation(string id)
        {
            var response = ConversationSender.GetConversation(id);
            ViewBag.GetDisplayName = response.DisplayName;
            ViewBag.GetId = response.Id;
            ViewBag.GetImageUrl = response.ImageUrl;
            ViewBag.GetSelf = response.Links.Self.Href;
            ViewBag.GetName = response.Name;
            ViewBag.GetProperties = response.Properties;
            ViewBag.GetTimestamp = response.Timestamp;

            return View("index");
        }

        [HttpPost]
        public IActionResult UpdateConversation(string id, string name, string displayName, string imageUrl)
        {
            var response = ConversationSender.UpdateConversation(id, name, displayName, imageUrl);
            ViewBag.UpdateDisplayName = response.DisplayName;
            ViewBag.UpdateId = response.Id;
            ViewBag.UpdateImageUrl = response.ImageUrl;
            ViewBag.UpdateSelf = response.Links.Self.Href;
            ViewBag.UpdateName = response.Name;
            ViewBag.UpdateProperties = response.Properties;
            ViewBag.UpdateTimestamp = response.Timestamp;
            return View("index");
        }

        [HttpPost]
        public IActionResult ListConversations()
        {
            var response = ConversationSender.ListConversation();
            ViewBag.ConversationCount = response.Embedded.Conversations.Count;
            return View("index");
        }

        [HttpPost]
        public IActionResult DeleteConversation(string id)
        {
            var response = ConversationSender.DeleteConversation(id);
            ViewBag.ConversationStatus = response == System.Net.HttpStatusCode.NoContent ? "Successfully Deleted" : "Something went wrong when deleting conversation " + response.ToString();
            return View("index");
        }

        [HttpPost]
        public IActionResult CreateUser(string name, string displayName, string imageUrl)
        {
            var response = ConversationSender.CreateUser(name, displayName, imageUrl);
            ViewBag.UserCreateDisplayName = response.DisplayName;
            ViewBag.UserCreateId = response.Id;
            ViewBag.UserCreateImageUrl = response.ImageUrl;
            ViewBag.UserCreateSelf = response.Links.Self.Href;
            ViewBag.UserCreateName = response.Name;

            return View("index");
        }

        [HttpPost]
        public IActionResult GetUser(string id)
        {
            var response = ConversationSender.GetUser(id);
            ViewBag.UserGetDisplayName = response.DisplayName;
            ViewBag.UserGetId = response.Id;
            ViewBag.UserGetImageUrl = response.ImageUrl;
            ViewBag.UserGetSelf = response.Links.Self.Href;
            ViewBag.UserGetName = response.Name;

            return View("index");
        }

        [HttpPost]
        public IActionResult ListUsers()
        {
            var response = ConversationSender.ListUsers();
            ViewBag.UserCount = response.Embedded.Users.Count;
            return View("index");
        }

        [HttpPost]
        public IActionResult UpdateUser(string id, string name, string displayName, string imageUrl)
        {
            var response = ConversationSender.UpdateUserRequest(id, name, displayName, imageUrl);
            ViewBag.UserUpdateDisplayName = response.DisplayName;
            ViewBag.UserUpdateId = response.Id;
            ViewBag.UserUpdateImageUrl = response.ImageUrl;
            ViewBag.UserUpdateSelf = response.Links.Self.Href;
            ViewBag.UserUpdateName = response.Name;
            return View("index");
        }

        [HttpPost]
        public IActionResult DeleteUser(string id)
        {
            var response = ConversationSender.DeleteUser(id);
            ViewBag.UserStatus = response == System.Net.HttpStatusCode.NoContent ? "Successfully deleted user " : "Something went wrong while deleting Conversation " + response.ToString();
            return View("index");
        }

        [HttpPost]
        public IActionResult CreateMemberWithUserId(string conversationId, string userId, CreateMemberRequestBase.CreateMemberAction action)
        {
            var response = ConversationSender.CreateMemberWithUserId(conversationId, userId, action);
            ViewBag.MemberCreateId = response.Id;
            ViewBag.MemberCreatename = response.Name;
            ViewBag.MemberCreateDisplayName = response.DisplayName;
            return View("index");
        }

        [HttpPost]
        public IActionResult CreateMemberWithUserName(string conversationId, string userName, CreateMemberRequestBase.CreateMemberAction action)
        {
            var response = ConversationSender.CreateMemberWithUserName(conversationId, userName, action);
            ViewBag.MemberCreateWithNameid = response.Id;
            ViewBag.MemberCreateWithNameName = response.Name;
            ViewBag.MemberCreateWithNameDisplayName = response.DisplayName;
            return View("index");
        }

        [HttpPost]
        public IActionResult UpdateMember(string conversationId, string memberId, UpdateMemberRequest.MemberState state)
        {
            var response = ConversationSender.UpdateMember(conversationId, memberId, state);
            ViewBag.MemberUpdateid = response.Id;
            ViewBag.MemberUpdateName = response.Name;
            ViewBag.MemberUpdateDisplayName = response.DisplayName;
            ViewBag.MemberUpdateState = response.State;
            return View("index");
        }

        [HttpPost]
        public IActionResult GetMember(string conversationId, string memberId)
        {
            var response = ConversationSender.GetMember(conversationId, memberId);
            ViewBag.MemberGetId = response.Id;
            ViewBag.MemberGetName = response.Name;
            ViewBag.MemberGetDisplayName = response.DisplayName;
            ViewBag.MemberGetState = response.State;
            return View("index");
        }

        [HttpPost]
        public IActionResult ListMembers(string conversationId)
        {
            var response = ConversationSender.ListMembers(conversationId);

            ViewBag.MemberCount = response.Embedded.Members.Count;
            return View("index");
        }

        [HttpPost]
        public IActionResult DeleteMember(string conversationId, string memberId)
        {
            var response = ConversationSender.DeleteMember(conversationId, memberId);

            ViewBag.MemberStatus = response == System.Net.HttpStatusCode.NoContent ? "Successfully deleted member" : "Encountered an issue while deleteing member : " + response.ToString();
            return View("index");
        }

        [HttpPost]
        public IActionResult CreateTextEvent(string conversationId, string to, string from, string text)
        {
            var response = ConversationSender.CreateEventWithText(to, from, text, conversationId);

            ViewBag.CreateTextEventId = response.Id;
            return View("index");
        }

        [HttpPost]
        public IActionResult CreateCustomEvent(string conversationid, string to, string from, string type)
        {
            var response = ConversationSender.CreateCustomEvent(type, to, from, conversationid);

            ViewBag.CreateCustomEventId = response.Id;
            return View("index");
        }

        [HttpPost]
        public IActionResult ListEvents(string conversationId, string start_id, string end_id)
        {
            var response = ConversationSender.ListEvents(conversationId, start_id, end_id);

            ViewBag.EventCount = response.Embedded.Events.Count;
            return View("index");
        }

        [HttpPost]
        public IActionResult GetEvent(string eventId, string conversationId)
        {
            var response = ConversationSender.GetEvent(conversationId, eventId);

            ViewBag.GetEventId = response.Id;
            return View("index");
        }

        [HttpPost]
        public IActionResult DeleteEvent(string eventId, string conversationId)
        {
            var response = ConversationSender.DeleteEvent(conversationId, eventId);
            ViewBag.EventStatus = response == System.Net.HttpStatusCode.NoContent ? "Event deleted successfully" : "Encountered a problem when deleting event " + response.ToString();
            return View("index");
        }
    }
}

NexmoDotnetCodeSnippets/Views/Home/Index.cshtml
<header>
    <h1>C# code samples for using Nexmo</h1>
    <h3>Everything you need to build connected applications with Nexmo</h3>
</header>

<div class="grid">
    <div class="item blog">
        <div class="content" value="Redirect" onclick="window.location='@Url.Action("Index", "SMS")'">
            <div class="title">
                <h3>SMS</h3>
            </div>
            <div class="desc">
                <p>Learn how to send and receive text messages with the Nexmo SMS API.</p>
            </div>
        </div>
    </div>
    <div class="item photo">
        <div class="content" value="Redirect" onclick="window.location='@Url.Action("Index", "Voice")'">
            <div class="title">
                <h3>Voice</h3>
            </div>
            <img class="photothumb" src="images/voice.png">
            <div class="desc">
                <p>The Nexmo Voice API is the easiest way to build high-quality voice applications in the Cloud.</p>
            </div>
        </div>
    </div>
    <div class="item project">
        <div class="content" value="Redirect" onclick="window.location='@Url.Action("Index", "Account")'">
            <div class="title">
                <h3>Account</h3>
            </div>
            <div class="desc">
                <img src="images/account.png">
                <p>Within your account you can check your balance, configure the account-level settings, and rotate your API secrets for security purposes. </p>
            </div>
        </div>
    </div>
    <div class="item photo">
        <div class="content" value="Redirect" onclick="window.location='@Url.Action("Index", "Verify")'">
            <div class="title">
                <h3>Verify</h3>
            </div>
            <img class="photothumb" src="images/verify.png">
            <div class="desc">
                <p>The Verify API enables you to confirm that you can contact a user at a specific number.</p>
            </div>
        </div>
    </div>
    <div class="item project">
        <div class="content" value="Redirect" onclick="window.location='@Url.Action("Index", "Numbers")'">
            <div class="title">
                <h3>Numbers</h3>
            </div>
            <div class="desc">
                <img src="images/sm.png">
                <p>A Nexmo virtual number is a telephone number that is not directly associated with a specific phone. It is programmable, enabling you to create custom call and messaging experiences for your users.</p>
            </div>
        </div>
    </div>
    <div class="item project">
        <div class="content">
            <div class="title" value="Redirect" onclick="window.location='@Url.Action("Index", "NumberInsights")'">
                <h3>Number Insight</h3>
            </div>
            <div class="desc">
                <img src="images/Ni.png">
                <p>Nexmo's Number Insight API delivers real-time intelligence about the validity, reachability and roaming status of a phone number and tells you how to format the number correctly in your application.</p>
            </div>
        </div>
    </div>
    <div class="item blog">
        <div class="content" value="Redirect" onclick="window.location='@Url.Action("Index", "Application")'">
            <div class="title">
                <h3>Application</h3>
            </div>
            <div class="desc">
                <p>A Nexmo application contains the security and configuration information you need to connect to Nexmo endpoints and easily use our products.</p>
            </div>
        </div>
    </div>
    <div class="item blog">
        <div class="content" value="Redirect" onclick="window.location='@Url.Action("Index", "Redact")'">
            <div class="title">
                <h3>Redact</h3>
            </div>
            <div class="desc">
                <p>Allows the management of personal data on Nexmo platform.</p>
            </div>
        </div>
    </div>
    <div class="item blog">
        <div class="content" value="Redirect" onclick="window.location = '@Url.Action("Index", "WebhookSwitch")'">
            <div class="title">
                <h3>Routes</h3>
            </div>
            <div class="desc">
                <p>Allows the management of webhook routes.</p>
            </div>
        </div>
    </div>
    <div class="item blog">
        <div class="content" value="Redirect" onclick="window.location = '@Url.Action("Index", "Conversation")'">
            <div class="title">
                <h3>Conversation</h3>
            </div>
            <div class="desc">
                <p>Allows management of Conversations, Users, Members, and Events</p>
            </div>
        </div>
    </div>
</div>