src/NexmoQuickStart/Controllers/NumberInsightController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Nexmo.Api;
using System.Diagnostics;
using Microsoft.AspNetCore.Http;
// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace NexmoQuickStart.Controllers
{
    public class NumberInsightController : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }
        // GET: /<controller>/
        [HttpGet]
        public IActionResult Basic()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Basic(string number)
        {
            var results = NumberInsight.RequestBasic(new NumberInsight.NumberInsightBasicRequest
            {
                number = number,
            });

            HttpContext.Session.SetString("requestID", results.request_id);
            HttpContext.Session.SetString("iNumber", results.international_format_number);
            HttpContext.Session.SetString("nNumber", results.national_format_number);
            HttpContext.Session.SetString("status", results.status_message);
            HttpContext.Session.SetString("country", results.country_name);
            HttpContext.Session.SetString("countryCode", results.country_code);

            return RedirectToAction("BasicResults");
        }

        [HttpGet]
        public IActionResult BasicResults()
        {

            ViewBag.requestID = HttpContext.Session.GetString("requestID");
            ViewBag.iNumber = HttpContext.Session.GetString("iNumber");
            ViewBag.nNumber = HttpContext.Session.GetString("nNumber");
            ViewBag.status = HttpContext.Session.GetString("status");
            ViewBag.country = HttpContext.Session.GetString("country");
            ViewBag.countryCode = HttpContext.Session.GetString("countryCode");

            return View();
        }


        [HttpGet]
        public IActionResult Standard()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Standard(string number)
        {
            var results = NumberInsight.RequestStandard(new NumberInsight.NumberInsightBasicRequest()
            {
                number = number,
            });
            HttpContext.Session.SetString("requestID", results.request_id);
            HttpContext.Session.SetString("iNumber", results.international_format_number);
            HttpContext.Session.SetString("nNumber", results.national_format_number);
            HttpContext.Session.SetString("country", results.country_name);
            HttpContext.Session.SetString("countryCode", results.country_code);
            HttpContext.Session.SetString("status", results.status_message);
            HttpContext.Session.SetString("currentCarrierName", results.original_carrier.name);
            HttpContext.Session.SetString("currentCarrierCode", results.current_carrier.network_code);
            HttpContext.Session.SetString("currentCarrierType", results.current_carrier.network_type);
            HttpContext.Session.SetString("currentCarrierCountry", results.current_carrier.country);
            HttpContext.Session.SetString("originalCarrierName", results.original_carrier.name);
            HttpContext.Session.SetString("originalCarrierCode", results.original_carrier.network_code);
            HttpContext.Session.SetString("originalCarrierType", results.original_carrier.network_type);
            HttpContext.Session.SetString("originalCarrierCountry", results.original_carrier.country);



            return RedirectToAction("StandardResults");
        }

        [HttpGet]
        public IActionResult StandardResults()
        {
            ViewBag.requestID = HttpContext.Session.GetString("requestID");
            ViewBag.iNumber = HttpContext.Session.GetString("iNumber");
            ViewBag.nNumber = HttpContext.Session.GetString("nNumber");
            ViewBag.status = HttpContext.Session.GetString("status");
            ViewBag.country = HttpContext.Session.GetString("country");
            ViewBag.countryCode = HttpContext.Session.GetString("countryCode");
            ViewBag.currentCarrierName = HttpContext.Session.GetString("currentCarrierName");
            ViewBag.currentCarrierCode = HttpContext.Session.GetString("currentCarrierCode");
            ViewBag.currentCarrierType = HttpContext.Session.GetString("currentCarrierType");
            ViewBag.currentCarrierCountry = HttpContext.Session.GetString("currentCarrierCountry");
            ViewBag.originalCarrierName = HttpContext.Session.GetString("originalCarrierName");
            ViewBag.originalCarrierCode = HttpContext.Session.GetString("originalCarrierCode");
            ViewBag.originalCarrierType = HttpContext.Session.GetString("originalCarrierType");
            ViewBag.originalCarrierCountry = HttpContext.Session.GetString("originalCarrierCountry");
            return View();
        }

    }

}

src/NexmoQuickStart/Controllers/SMSController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Nexmo.Api;
using System.Net;
using Microsoft.AspNetCore.Http;
using System.Diagnostics;
using Microsoft.Extensions.Configuration;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace NexmoQuickStart.Controllers
{
    public class SMSController : Controller
    {
        public IConfiguration configuration;

        public IActionResult Index()
        {
            return View();
        }
        // GET: /<controller>/
        public IActionResult Send()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Send(string to, string text)
        {
            var results = SMS.Send(new SMS.SMSRequest
            {
                
                from = Configuration.Instance.Settings["appSettings:NEXMO_FROM_NUMBER"],
                to = to,
                text = text
            });
            return View("Index");
        }

        [HttpGet]
        public IActionResult Recieve([FromQuery]SMS.SMSInbound response)
        {

            if (null != response.to && null != response.msisdn)
            {
                Debug.WriteLine("-------------------------------------------------------------------------");
                Debug.WriteLine("INCOMING TEXT");
                Debug.WriteLine("From: " + response.msisdn);
                Debug.WriteLine(" Message: " + response.text);
                Debug.WriteLine("-------------------------------------------------------------------------");
                return StatusCode(200);
            }
            else
            {
                Debug.WriteLine("-------------------------------------------------------------------------");
                Debug.WriteLine("Endpoint was hit.");
                Debug.WriteLine("-------------------------------------------------------------------------");
                return StatusCode(200);
;            }

        }
        
        [HttpGet]
        public ActionResult DLR([FromQuery]SMS.SMSDeliveryReceipt response)
        {

            Debug.WriteLine("-------------------------------------------------------------------------");
            Debug.WriteLine("DELIVERY RECIEPT");
            Debug.WriteLine("Message ID: " + response.messageId);
            Debug.WriteLine("From: " + response.msisdn);
            Debug.WriteLine("To: " + response.to);
            Debug.WriteLine("Status: " + response.status);
            Debug.WriteLine("-------------------------------------------------------------------------");
            return StatusCode(200);
        }
    }
}

src/NexmoQuickStart/Controllers/SearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Nexmo.Api;
// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace NexmoQuickStart.Controllers
{
    public class SearchController : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }
        // GET: /<controller>/
        [HttpGet]
        public IActionResult SearchMessage()
        {
            return View();
        }
        [HttpPost]
        public IActionResult SearchMessage(string messageID)
        {
            var message = Search.GetMessage(messageID);
            if (message.messageId != null)
            {
                ViewData.Add("message", message);
            }
            else {
                bool notFound = true;
                ViewData.Add("notFound", notFound);
            }
            return View();
        }
        [HttpGet]
        public IActionResult SearchRejection()
        {
            return View();
        }
        [HttpPost]
        public IActionResult SearchRejection(string messageID, string number, DateTime rejectionDate )
        {

            string date = rejectionDate.Year + "-" + rejectionDate.Month + "-" + rejectionDate.Day;
          
            var msgs = Search.GetRejections(new Search.SearchRequest
            {
                date = date,
                to = number
            });
            ViewData.Add("items", msgs.items);
            return View();
        }
    }
}

src/NexmoQuickStart/Controllers/VerifyController.cs
using System;

using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Nexmo.Api;
using System.Windows;
// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace NexmoQuickStart.Controllers
{
    public class VerifyController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public IActionResult Start() 
        {
            return View();
        }
        [HttpPost]
        public IActionResult Start(string to)
        {
            var start = NumberVerify.Verify(new NumberVerify.VerifyRequest
            {
                number = to,
                brand = "NexmoQS"
            });
            HttpContext.Session.SetString("requestID", start.request_id);

            return RedirectToAction("Check");
        }
        [HttpGet]
        public IActionResult Check()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Check(string code)
        {
           var result = NumberVerify.Check(new NumberVerify.CheckRequest
            {
                request_id = HttpContext.Session.GetString("requestID"),
                code = code
            });
            
            if (result.status == "0")
            {
                ViewBag.Message = "Verification Sucessful";
            }
            else
            {
                ViewBag.Message = result.error_text;
            }
            return View();

        }

        [HttpGet]
        public IActionResult Search()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Search(string requestID)
        {
            var search = NumberVerify.Search(new NumberVerify.SearchRequest
            {
                request_id = requestID
            });
            ViewBag.error_text = search.error_text;
            ViewBag.status = search.status;
       
            return View();
        }

        [HttpGet]
        public IActionResult Cancel()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Cancel(string requestID)
        {
            var results = NumberVerify.Control(new NumberVerify.ControlRequest
            {
                request_id = requestID,
                cmd = "cancel"
            });
            ViewBag.status = results.status;
            return View();
        }
    }
}

src/NexmoQuickStart/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NexmoQuickStart</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">NexmoQuickStart</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="SMS" asp-action="Index">SMS</a></li>
                    <li><a asp-area="" asp-controller="Voice" asp-action="Index">Voice</a></li>
                    <li><a asp-area="" asp-controller="Verify" asp-action="Index">Verify</a></li>
                    <li><a asp-area="" asp-controller="NumberInsight" asp-action="Index">Number Insight</a></li>
                    <li><a asp-area="" asp-controller="Search" asp-action="Index">Search</a></li>

                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - NexmoQuickStart</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>